"use strict"

var right = {}
module.exports = right

right["archon"] = {
	title:"archon",
	titleLevel:1,
	editAllianceTitleName:true,
	editAllianceBasicInfo:true,
	editAllianceNotice:true,
	editAllianceDescription:true,
	editAllianceJoinType:true,
	editAllianceMemberTitle:true,
	kickAllianceMemberOff:true,
	sendAllianceMail:true,
	handleJoinAllianceRequest:true,
	inviteToJoinAlliance:true,
	upgradeAllianceBuilding:true,
	editAllianceTerrian:true,
	upgradeAllianceVillage:true,
	moveAllianceBuilding:true,
	distroyAllianceDecorate:true
}
right["general"] = {
	title:"general",
	titleLevel:2,
	editAllianceTitleName:false,
	editAllianceBasicInfo:false,
	editAllianceNotice:false,
	editAllianceDescription:false,
	editAllianceJoinType:false,
	editAllianceMemberTitle:false,
	kickAllianceMemberOff:false,
	sendAllianceMail:false,
	handleJoinAllianceRequest:false,
	inviteToJoinAlliance:false,
	upgradeAllianceBuilding:false,
	editAllianceTerrian:false,
	upgradeAllianceVillage:false,
	moveAllianceBuilding:false,
	distroyAllianceDecorate:false
}
right["quartermaster"] = {
	title:"quartermaster",
	titleLevel:3,
	editAllianceTitleName:false,
	editAllianceBasicInfo:false,
	editAllianceNotice:false,
	editAllianceDescription:false,
	editAllianceJoinType:false,
	editAllianceMemberTitle:false,
	kickAllianceMemberOff:false,
	sendAllianceMail:false,
	handleJoinAllianceRequest:false,
	inviteToJoinAlliance:false,
	upgradeAllianceBuilding:false,
	editAllianceTerrian:false,
	upgradeAllianceVillage:false,
	moveAllianceBuilding:false,
	distroyAllianceDecorate:false
}
right["supervisor"] = {
	title:"supervisor",
	titleLevel:4,
	editAllianceTitleName:false,
	editAllianceBasicInfo:false,
	editAllianceNotice:false,
	editAllianceDescription:false,
	editAllianceJoinType:false,
	editAllianceMemberTitle:false,
	kickAllianceMemberOff:false,
	sendAllianceMail:false,
	handleJoinAllianceRequest:false,
	inviteToJoinAlliance:false,
	upgradeAllianceBuilding:false,
	editAllianceTerrian:false,
	upgradeAllianceVillage:false,
	moveAllianceBuilding:false,
	distroyAllianceDecorate:false
}
right["elite"] = {
	title:"elite",
	titleLevel:5,
	editAllianceTitleName:false,
	editAllianceBasicInfo:false,
	editAllianceNotice:false,
	editAllianceDescription:false,
	editAllianceJoinType:false,
	editAllianceMemberTitle:false,
	kickAllianceMemberOff:false,
	sendAllianceMail:false,
	handleJoinAllianceRequest:false,
	inviteToJoinAlliance:false,
	upgradeAllianceBuilding:false,
	editAllianceTerrian:false,
	upgradeAllianceVillage:false,
	moveAllianceBuilding:false,
	distroyAllianceDecorate:false
}
right["member"] = {
	title:"member",
	titleLevel:6,
	editAllianceTitleName:false,
	editAllianceBasicInfo:false,
	editAllianceNotice:false,
	editAllianceDescription:false,
	editAllianceJoinType:false,
	editAllianceMemberTitle:false,
	kickAllianceMemberOff:false,
	sendAllianceMail:false,
	handleJoinAllianceRequest:false,
	inviteToJoinAlliance:false,
	upgradeAllianceBuilding:false,
	editAllianceTerrian:false,
	upgradeAllianceVillage:false,
	moveAllianceBuilding:false,
	distroyAllianceDecorate:false
}
