"use strict"

var equipments = {}
module.exports = equipments

equipments["redCrown_s1"] = {
	name:"redCrown_s1",
	usedFor:"redDragon",
	maxStar:1,
	category:"crown",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["blueCrown_s1"] = {
	name:"blueCrown_s1",
	usedFor:"blueDragon",
	maxStar:1,
	category:"crown",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["greenCrown_s1"] = {
	name:"greenCrown_s1",
	usedFor:"greenDragon",
	maxStar:1,
	category:"crown",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["redCrown_s2"] = {
	name:"redCrown_s2",
	usedFor:"redDragon",
	maxStar:2,
	category:"crown",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["blueCrown_s2"] = {
	name:"blueCrown_s2",
	usedFor:"blueDragon",
	maxStar:2,
	category:"crown",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["greenCrown_s2"] = {
	name:"greenCrown_s2",
	usedFor:"greenDragon",
	maxStar:2,
	category:"crown",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["redCrown_s3"] = {
	name:"redCrown_s3",
	usedFor:"redDragon",
	maxStar:3,
	category:"crown",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["blueCrown_s3"] = {
	name:"blueCrown_s3",
	usedFor:"blueDragon",
	maxStar:3,
	category:"crown",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["greenCrown_s3"] = {
	name:"greenCrown_s3",
	usedFor:"greenDragon",
	maxStar:3,
	category:"crown",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["redCrown_s4"] = {
	name:"redCrown_s4",
	usedFor:"redDragon",
	maxStar:4,
	category:"crown",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["blueCrown_s4"] = {
	name:"blueCrown_s4",
	usedFor:"blueDragon",
	maxStar:4,
	category:"crown",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["greenCrown_s4"] = {
	name:"greenCrown_s4",
	usedFor:"greenDragon",
	maxStar:4,
	category:"crown",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["redCrown_s5"] = {
	name:"redCrown_s5",
	usedFor:"redDragon",
	maxStar:5,
	category:"crown",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["blueCrown_s5"] = {
	name:"blueCrown_s5",
	usedFor:"blueDragon",
	maxStar:5,
	category:"crown",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["greenCrown_s5"] = {
	name:"greenCrown_s5",
	usedFor:"greenDragon",
	maxStar:5,
	category:"crown",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["redChest_s2"] = {
	name:"redChest_s2",
	usedFor:"redDragon",
	maxStar:2,
	category:"chest",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["blueChest_s2"] = {
	name:"blueChest_s2",
	usedFor:"blueDragon",
	maxStar:2,
	category:"chest",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["greenChest_s2"] = {
	name:"greenChest_s2",
	usedFor:"greenDragon",
	maxStar:2,
	category:"chest",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["redChest_s3"] = {
	name:"redChest_s3",
	usedFor:"redDragon",
	maxStar:3,
	category:"chest",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["blueChest_s3"] = {
	name:"blueChest_s3",
	usedFor:"blueDragon",
	maxStar:3,
	category:"chest",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["greenChest_s3"] = {
	name:"greenChest_s3",
	usedFor:"greenDragon",
	maxStar:3,
	category:"chest",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["redChest_s4"] = {
	name:"redChest_s4",
	usedFor:"redDragon",
	maxStar:4,
	category:"chest",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["blueChest_s4"] = {
	name:"blueChest_s4",
	usedFor:"blueDragon",
	maxStar:4,
	category:"chest",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["greenChest_s4"] = {
	name:"greenChest_s4",
	usedFor:"greenDragon",
	maxStar:4,
	category:"chest",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["redChest_s5"] = {
	name:"redChest_s5",
	usedFor:"redDragon",
	maxStar:5,
	category:"chest",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["blueChest_s5"] = {
	name:"blueChest_s5",
	usedFor:"blueDragon",
	maxStar:5,
	category:"chest",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["greenChest_s5"] = {
	name:"greenChest_s5",
	usedFor:"greenDragon",
	maxStar:5,
	category:"chest",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["redSting_s2"] = {
	name:"redSting_s2",
	usedFor:"redDragon",
	maxStar:2,
	category:"sting",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["blueSting_s2"] = {
	name:"blueSting_s2",
	usedFor:"blueDragon",
	maxStar:2,
	category:"sting",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["greenSting_s2"] = {
	name:"greenSting_s2",
	usedFor:"greenDragon",
	maxStar:2,
	category:"sting",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["redSting_s3"] = {
	name:"redSting_s3",
	usedFor:"redDragon",
	maxStar:3,
	category:"sting",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["blueSting_s3"] = {
	name:"blueSting_s3",
	usedFor:"blueDragon",
	maxStar:3,
	category:"sting",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["greenSting_s3"] = {
	name:"greenSting_s3",
	usedFor:"greenDragon",
	maxStar:3,
	category:"sting",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["redSting_s4"] = {
	name:"redSting_s4",
	usedFor:"redDragon",
	maxStar:4,
	category:"sting",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["blueSting_s4"] = {
	name:"blueSting_s4",
	usedFor:"blueDragon",
	maxStar:4,
	category:"sting",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["greenSting_s4"] = {
	name:"greenSting_s4",
	usedFor:"greenDragon",
	maxStar:4,
	category:"sting",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["redSting_s5"] = {
	name:"redSting_s5",
	usedFor:"redDragon",
	maxStar:5,
	category:"sting",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["blueSting_s5"] = {
	name:"blueSting_s5",
	usedFor:"blueDragon",
	maxStar:5,
	category:"sting",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["greenSting_s5"] = {
	name:"greenSting_s5",
	usedFor:"greenDragon",
	maxStar:5,
	category:"sting",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["redOrd_s2"] = {
	name:"redOrd_s2",
	usedFor:"redDragon",
	maxStar:2,
	category:"orb",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["blueOrd_s2"] = {
	name:"blueOrd_s2",
	usedFor:"blueDragon",
	maxStar:2,
	category:"orb",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["greenOrd_s2"] = {
	name:"greenOrd_s2",
	usedFor:"greenDragon",
	maxStar:2,
	category:"orb",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["redOrd_s3"] = {
	name:"redOrd_s3",
	usedFor:"redDragon",
	maxStar:3,
	category:"orb",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["blueOrd_s3"] = {
	name:"blueOrd_s3",
	usedFor:"blueDragon",
	maxStar:3,
	category:"orb",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["greenOrd_s3"] = {
	name:"greenOrd_s3",
	usedFor:"greenDragon",
	maxStar:3,
	category:"orb",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["redOrd_s4"] = {
	name:"redOrd_s4",
	usedFor:"redDragon",
	maxStar:4,
	category:"orb",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["blueOrd_s4"] = {
	name:"blueOrd_s4",
	usedFor:"blueDragon",
	maxStar:4,
	category:"orb",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["greenOrd_s4"] = {
	name:"greenOrd_s4",
	usedFor:"greenDragon",
	maxStar:4,
	category:"orb",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["redOrd_s5"] = {
	name:"redOrd_s5",
	usedFor:"redDragon",
	maxStar:5,
	category:"orb",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["blueOrd_s5"] = {
	name:"blueOrd_s5",
	usedFor:"blueDragon",
	maxStar:5,
	category:"orb",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["greenOrd_s5"] = {
	name:"greenOrd_s5",
	usedFor:"greenDragon",
	maxStar:5,
	category:"orb",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["redArmguard_s1"] = {
	name:"redArmguard_s1",
	usedFor:"redDragon",
	maxStar:1,
	category:"armguardLeft,armguardRight",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["blueArmguard_s1"] = {
	name:"blueArmguard_s1",
	usedFor:"blueDragon",
	maxStar:1,
	category:"armguardLeft,armguardRight",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["greenArmguard_s1"] = {
	name:"greenArmguard_s1",
	usedFor:"greenDragon",
	maxStar:1,
	category:"armguardLeft,armguardRight",
	resolveLExp:15,
	resolveMExp:10,
	resolveSExp:5,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:320,
	makeTime:1600
}
equipments["redArmguard_s2"] = {
	name:"redArmguard_s2",
	usedFor:"redDragon",
	maxStar:2,
	category:"armguardLeft,armguardRight",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["blueArmguard_s2"] = {
	name:"blueArmguard_s2",
	usedFor:"blueDragon",
	maxStar:2,
	category:"armguardLeft,armguardRight",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["greenArmguard_s2"] = {
	name:"greenArmguard_s2",
	usedFor:"greenDragon",
	maxStar:2,
	category:"armguardLeft,armguardRight",
	resolveLExp:30,
	resolveMExp:20,
	resolveSExp:10,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:1280,
	makeTime:3600
}
equipments["redArmguard_s3"] = {
	name:"redArmguard_s3",
	usedFor:"redDragon",
	maxStar:3,
	category:"armguardLeft,armguardRight",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["blueArmguard_s3"] = {
	name:"blueArmguard_s3",
	usedFor:"blueDragon",
	maxStar:3,
	category:"armguardLeft,armguardRight",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["greenArmguard_s3"] = {
	name:"greenArmguard_s3",
	usedFor:"greenDragon",
	maxStar:3,
	category:"armguardLeft,armguardRight",
	resolveLExp:75,
	resolveMExp:50,
	resolveSExp:25,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:5120,
	makeTime:7200
}
equipments["redArmguard_s4"] = {
	name:"redArmguard_s4",
	usedFor:"redDragon",
	maxStar:4,
	category:"armguardLeft,armguardRight",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["blueArmguard_s4"] = {
	name:"blueArmguard_s4",
	usedFor:"blueDragon",
	maxStar:4,
	category:"armguardLeft,armguardRight",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["greenArmguard_s4"] = {
	name:"greenArmguard_s4",
	usedFor:"greenDragon",
	maxStar:4,
	category:"armguardLeft,armguardRight",
	resolveLExp:150,
	resolveMExp:100,
	resolveSExp:50,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:20480,
	makeTime:12000
}
equipments["redArmguard_s5"] = {
	name:"redArmguard_s5",
	usedFor:"redDragon",
	maxStar:5,
	category:"armguardLeft,armguardRight",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["blueArmguard_s5"] = {
	name:"blueArmguard_s5",
	usedFor:"blueDragon",
	maxStar:5,
	category:"armguardLeft,armguardRight",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
equipments["greenArmguard_s5"] = {
	name:"greenArmguard_s5",
	usedFor:"greenDragon",
	maxStar:5,
	category:"armguardLeft,armguardRight",
	resolveLExp:300,
	resolveMExp:200,
	resolveSExp:100,
	materials:"ingo_1:1,redCrystal_1:1",
	coin:81920,
	makeTime:16000
}
