"use strict"

var buff = {}
module.exports = buff

buff["masterOfDefender_1"] = {
	name:"masterOfDefender_1",
	effect:8,
	type:"masterOfDefender",
	order:1,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["masterOfDefender_2"] = {
	name:"masterOfDefender_2",
	effect:24,
	type:"masterOfDefender",
	order:2,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["masterOfDefender_3"] = {
	name:"masterOfDefender_3",
	effect:72,
	type:"masterOfDefender",
	order:3,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["quarterMaster_1"] = {
	name:"quarterMaster_1",
	effect:8,
	type:"quarterMaster",
	order:4,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["quarterMaster_2"] = {
	name:"quarterMaster_2",
	effect:24,
	type:"quarterMaster",
	order:5,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["quarterMaster_3"] = {
	name:"quarterMaster_3",
	effect:72,
	type:"quarterMaster",
	order:6,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["fogOfTrick_1"] = {
	name:"fogOfTrick_1",
	effect:8,
	type:"fogOfTrick",
	order:7,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["fogOfTrick_2"] = {
	name:"fogOfTrick_2",
	effect:24,
	type:"fogOfTrick",
	order:8,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["fogOfTrick_3"] = {
	name:"fogOfTrick_3",
	effect:72,
	type:"fogOfTrick",
	order:9,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["woodBonus_1"] = {
	name:"woodBonus_1",
	effect:8,
	type:"woodBonus",
	order:10,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["woodBonus_2"] = {
	name:"woodBonus_2",
	effect:24,
	type:"woodBonus",
	order:11,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["woodBonus_3"] = {
	name:"woodBonus_3",
	effect:72,
	type:"woodBonus",
	order:12,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["stoneBonus_1"] = {
	name:"stoneBonus_1",
	effect:8,
	type:"stoneBonus",
	order:13,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["stoneBonus_2"] = {
	name:"stoneBonus_2",
	effect:24,
	type:"stoneBonus",
	order:14,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["stoneBonus_3"] = {
	name:"stoneBonus_3",
	effect:72,
	type:"stoneBonus",
	order:15,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["ironBonus_1"] = {
	name:"ironBonus_1",
	effect:8,
	type:"ironBonus",
	order:16,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["ironBonus_2"] = {
	name:"ironBonus_2",
	effect:24,
	type:"ironBonus",
	order:17,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["ironBonus_3"] = {
	name:"ironBonus_3",
	effect:72,
	type:"ironBonus",
	order:18,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["foodBonus_1"] = {
	name:"foodBonus_1",
	effect:8,
	type:"foodBonus",
	order:19,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["foodBonus_2"] = {
	name:"foodBonus_2",
	effect:24,
	type:"foodBonus",
	order:20,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["foodBonus_3"] = {
	name:"foodBonus_3",
	effect:72,
	type:"foodBonus",
	order:21,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["taxesBonus_1"] = {
	name:"taxesBonus_1",
	effect:8,
	type:"taxesBonus",
	order:22,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["taxesBonus_2"] = {
	name:"taxesBonus_2",
	effect:24,
	type:"taxesBonus",
	order:23,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["taxesBonus_3"] = {
	name:"taxesBonus_3",
	effect:72,
	type:"taxesBonus",
	order:24,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["citizenBonus_1"] = {
	name:"citizenBonus_1",
	effect:8,
	type:"citizenBonus",
	order:25,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["citizenBonus_2"] = {
	name:"citizenBonus_2",
	effect:24,
	type:"citizenBonus",
	order:26,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["citizenBonus_3"] = {
	name:"citizenBonus_3",
	effect:72,
	type:"citizenBonus",
	order:27,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonExpBonus_1"] = {
	name:"dragonExpBonus_1",
	effect:8,
	type:"dragonExpBonus",
	order:28,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonExpBonus_2"] = {
	name:"dragonExpBonus_2",
	effect:24,
	type:"dragonExpBonus",
	order:29,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonExpBonus_3"] = {
	name:"dragonExpBonus_3",
	effect:72,
	type:"dragonExpBonus",
	order:30,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["troopSizeBonus_1"] = {
	name:"troopSizeBonus_1",
	effect:8,
	type:"troopSizeBonus",
	order:31,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["troopSizeBonus_2"] = {
	name:"troopSizeBonus_2",
	effect:24,
	type:"troopSizeBonus",
	order:32,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["troopSizeBonus_3"] = {
	name:"troopSizeBonus_3",
	effect:72,
	type:"troopSizeBonus",
	order:33,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonHpBonus_1"] = {
	name:"dragonHpBonus_1",
	effect:8,
	type:"dragonHpBonus",
	order:34,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonHpBonus_2"] = {
	name:"dragonHpBonus_2",
	effect:24,
	type:"dragonHpBonus",
	order:35,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["dragonHpBonus_3"] = {
	name:"dragonHpBonus_3",
	effect:72,
	type:"dragonHpBonus",
	order:36,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["marchSpeedBonus_1"] = {
	name:"marchSpeedBonus_1",
	effect:8,
	type:"marchSpeedBonus",
	order:37,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["marchSpeedBonus_2"] = {
	name:"marchSpeedBonus_2",
	effect:24,
	type:"marchSpeedBonus",
	order:38,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["marchSpeedBonus_3"] = {
	name:"marchSpeedBonus_3",
	effect:72,
	type:"marchSpeedBonus",
	order:39,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["unitHpBonus_1"] = {
	name:"unitHpBonus_1",
	effect:8,
	type:"unitHpBonus",
	order:40,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["unitHpBonus_2"] = {
	name:"unitHpBonus_2",
	effect:24,
	type:"unitHpBonus",
	order:41,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["unitHpBonus_3"] = {
	name:"unitHpBonus_3",
	effect:72,
	type:"unitHpBonus",
	order:42,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["infantryAtkBonus_1"] = {
	name:"infantryAtkBonus_1",
	effect:8,
	type:"infantryAtkBonus",
	order:43,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["infantryAtkBonus_2"] = {
	name:"infantryAtkBonus_2",
	effect:24,
	type:"infantryAtkBonus",
	order:44,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["infantryAtkBonus_3"] = {
	name:"infantryAtkBonus_3",
	effect:72,
	type:"infantryAtkBonus",
	order:45,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["archerAtkBonus_1"] = {
	name:"archerAtkBonus_1",
	effect:8,
	type:"archerAtkBonus",
	order:46,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["archerAtkBonus_2"] = {
	name:"archerAtkBonus_2",
	effect:24,
	type:"archerAtkBonus",
	order:47,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["archerAtkBonus_3"] = {
	name:"archerAtkBonus_3",
	effect:72,
	type:"archerAtkBonus",
	order:48,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["cavalryAtkBonus_1"] = {
	name:"cavalryAtkBonus_1",
	effect:8,
	type:"cavalryAtkBonus",
	order:49,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["cavalryAtkBonus_2"] = {
	name:"cavalryAtkBonus_2",
	effect:24,
	type:"cavalryAtkBonus",
	order:50,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["cavalryAtkBonus_3"] = {
	name:"cavalryAtkBonus_3",
	effect:72,
	type:"cavalryAtkBonus",
	order:51,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["siegeAtkBonus_1"] = {
	name:"siegeAtkBonus_1",
	effect:8,
	type:"siegeAtkBonus",
	order:52,
	isSell:true,
	price:10,
	isSellInAlliance:true,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["siegeAtkBonus_2"] = {
	name:"siegeAtkBonus_2",
	effect:24,
	type:"siegeAtkBonus",
	order:53,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
buff["siegeAtkBonus_3"] = {
	name:"siegeAtkBonus_3",
	effect:72,
	type:"siegeAtkBonus",
	order:54,
	isSell:true,
	price:10,
	isSellInAlliance:false,
	sellPriceInAlliance:200,
	buyPriceInAlliance:200,
	isAdvancedItem:false
}
