var special = {}
module.exports = special

special["skeletonWarrior"] = {
	"type":"skeletonWarrior",
	"description":"骷髅勇士",
	"specialMaterials":"deathHand,heroBones,soulStone",
	"star":2,
	"power":10,
	"atkInfs":38,
	"atkHunter":30,
	"atkCavalry":19,
	"atkSiege":57,
	"atkWall":45,
	"hp":50,
	"load":17,
	"march":50,
	"upkeep":5,
	"population":1
}
special["skeletonArcher"] = {
	"type":"skeletonArcher",
	"description":"骷髅射手",
	"specialMaterials":"deathHand,heroBones,magicBox",
	"star":2,
	"power":10,
	"atkInfs":95,
	"atkHunter":63,
	"atkCavalry":76,
	"atkSiege":32,
	"atkWall":51,
	"hp":31,
	"load":18,
	"march":64,
	"upkeep":18,
	"population":1
}
special["deathKnight"] = {
	"type":"deathKnight",
	"description":"死亡骑士",
	"specialMaterials":"deathHand,heroBones,magicBox",
	"star":3,
	"power":26,
	"atkInfs":174,
	"atkHunter":58,
	"atkCavalry":116,
	"atkSiege":140,
	"atkWall":93,
	"hp":87,
	"load":48,
	"march":80,
	"upkeep":48,
	"population":2
}
special["meatWagon"] = {
	"type":"meatWagon",
	"description":"绞肉机",
	"specialMaterials":"heroBones,soulStone,magicBox",
	"star":3,
	"power":48,
	"atkInfs":224,
	"atkHunter":336,
	"atkCavalry":140,
	"atkSiege":280,
	"atkWall":420,
	"hp":135,
	"load":96,
	"march":52,
	"upkeep":96,
	"population":4
}
special["priest"] = {
	"type":"priest",
	"description":"牧师",
	"specialMaterials":"confessionHood,brightRing,holyBook",
	"star":3,
	"power":16,
	"atkInfs":39,
	"atkHunter":20,
	"atkCavalry":31,
	"atkSiege":47,
	"atkWall":58,
	"hp":80,
	"load":27,
	"march":52,
	"upkeep":27,
	"population":1
}
special["demonHunter"] = {
	"type":"demonHunter",
	"description":"猎魔人",
	"specialMaterials":"confessionHood,brightRing,brightAlloy",
	"star":3,
	"power":16,
	"atkInfs":78,
	"atkHunter":65,
	"atkCavalry":98,
	"atkSiege":52,
	"atkWall":33,
	"hp":49,
	"load":28,
	"march":72,
	"upkeep":28,
	"population":1
}
special["paladin"] = {
	"type":"paladin",
	"description":"圣骑士",
	"specialMaterials":"confessionHood,holyBook,brightAlloy",
	"star":3,
	"power":27,
	"atkInfs":87,
	"atkHunter":58,
	"atkCavalry":72,
	"atkSiege":108,
	"atkWall":36,
	"hp":150,
	"load":53,
	"march":75,
	"upkeep":53,
	"population":2
}
special["steamTank"] = {
	"type":"steamTank",
	"description":"蒸汽坦克",
	"specialMaterials":"brightRing,holyBook,brightAlloy",
	"star":3,
	"power":58,
	"atkInfs":124,
	"atkHunter":372,
	"atkCavalry":199,
	"atkSiege":248,
	"atkWall":298,
	"hp":186,
	"load":106,
	"march":48,
	"upkeep":106,
	"population":4
}
